function [featureTable,outputTable] = DFD_ML_V3_PB(inputData)
%DIAGNOSTICFEATURES recreates results in Diagnostic Feature Designer.
%
% Input:
%  inputData: A table or a cell array of tables/matrices containing the
%  data as those imported into the app.
%
% Output:
%  featureTable: A table containing all features and condition variables.
%  outputTable: A table containing the computation results.
%
% This function computes spectra:
%  Vibration_ps/SpectrumData
%
% This function computes features:
%  Vibration_ps_bearing/PeakAmp6
%  Vibration_ps_bearing/BandPower6
%  Vibration_ps_bearing/PeakAmp7
%  Vibration_ps_bearing/BandPower7
%
% This function computes condition variables:
%  Tachometer_rpm
%
% Organization of the function:
% 1. Compute signals/spectra/features
% 2. Extract computed features into a table
%
% Modify the function to add or remove data processing, feature generation
% or ranking operations.

% Auto-generated by MATLAB on 11-Dec-2023 15:45:15

% Create output ensemble.
outputEnsemble = workspaceEnsemble(inputData,'DataVariables',["Vibration";"Tachometer"],'ConditionVariables',"faultCode");

% Reset the ensemble to read from the beginning of the ensemble.
reset(outputEnsemble);

% Append new signal or feature names to DataVariables.
outputEnsemble.DataVariables = unique([outputEnsemble.DataVariables;"Tachometer_rpm";"Vibration_ps";"Vibration_ps_bearing"],'stable');

% Set SelectedVariables to select variables to read from the ensemble.
outputEnsemble.SelectedVariables = ["Vibration","Tachometer"];

% Loop through all ensemble members to read and write data.
while hasdata(outputEnsemble)
    % Read one member.
    member = read(outputEnsemble);

    % Get all input variables.
    Vibration = readMemberData(member,"Vibration",["Time","Vibration"]);
    Tachometer = readMemberData(member,"Tachometer",["Time","Tachometer"]);

    % Initialize a table to store results.
    memberResult = table;

    %% TSA
    try
        % Convert any datetime data to duration.
        if isdatetime(Vibration.Time)
            tVib = Vibration.Time - Vibration.Time(1);
        else
            tVib = Vibration.Time;
        end

        % Compute tacho pulse times in units of seconds.
        tNumeric = time2num(Tachometer.Time,"seconds");
        Fs = effectivefs(tNumeric);
        [~,~,tp] = tachorpm(Tachometer.Tachometer,Fs,'PulsesPerRev',1,'FitType','linear');
        tp = tp + tNumeric(1);

        % Compute the time-synchronous average and the nominal rpm.
        [xTsa,tTsa,~,rpm] = tsa(Vibration.Vibration,tVib,tp, ...
            'Method','linear','PulsesPerRotation',1,'NumRotations',1);

        % Store the nominal rpm as a condition variable.
        Tachometer_rpm = rpm;
    catch
        % Store the nominal rpm as a condition variable.
        Tachometer_rpm = NaN;
    end

    % Append computed results to the member table.
    memberResult = [memberResult, ...
        table(Tachometer_rpm,'VariableNames',{'Tachometer_rpm'})]; %#ok<AGROW>

    %% PowerSpectrum
    try
        % Get units to use in computed spectrum.
        tuReal = "seconds";

        % Compute effective sampling rate.
        tNumeric = time2num(Vibration.Time,tuReal);
        [Fs,irregular] = effectivefs(tNumeric);
        Ts = 1/Fs;

        % Resample non-uniform signals.
        x_raw = Vibration.Vibration;
        if irregular
            x = resample(x_raw,tNumeric,Fs,'linear');
        else
            x = x_raw;
        end

        % Set Welch spectrum parameters.
        L = fix(length(x)/4.5);
        noverlap = fix(L*50/100);
        win = hamming(L);

        % Compute the power spectrum.
        f = linspace(0,10000,1000);
        f = f*funitconv('Hz','cycles/TimeUnit','seconds');
        [ps,f] = pwelch(x,win,noverlap,f(:),Fs);
        ps = 2*ps;
        w = 2*pi*f;

        % Convert frequency unit.
        factor = funitconv('rad/TimeUnit', 'Hz', 'seconds');
        w = factor*w;
        Fs = 2*pi*factor*Fs;

        % Remove frequencies above Nyquist frequency.
        I = w<=(Fs/2+1e4*eps);
        w = w(I);
        ps = ps(I);

        % Configure the computed spectrum.
        ps = table(w, ps, 'VariableNames', {'Frequency', 'SpectrumData'});
        ps.Properties.VariableUnits = {'Hz', ''};
        ps = addprop(ps, {'SampleFrequency'}, {'table'});
        ps.Properties.CustomProperties.SampleFrequency = Fs;
        Vibration_ps = ps;
    catch
        Vibration_ps = table(NaN, NaN, 'VariableNames', {'Frequency', 'SpectrumData'});
    end

    % Append computed results to the member table.
    memberResult = [memberResult, ...
        table({Vibration_ps},'VariableNames',{'Vibration_ps'})]; %#ok<AGROW>

    %% BearingFaultsFeatures
    try
        % Convert the speed value from RPM to Hz.
        speed = Tachometer_rpm * 1.666667e-02;

        % Compute the fault frequency bands.
        [FB, info] = bearingFaultBands(speed, 8, 6.750000e+00, 2.905000e+01, 0, ...
        	'Sidebands', [0 1], 'Folding', true);

        idx = true(8, 1);

        % Apply the filter to the fault bands.
        FB_filtered = FB(idx, :);
        info_filtered = struct;
        info_filtered.Centers = info.Centers(idx);
        info_filtered.Labels = info.Labels(idx);
        info_filtered.FaultGroups = info.FaultGroups(idx);

        % Compute spectral fault band metrics.
        sd = Vibration_ps.SpectrumData;
        w = Vibration_ps.Frequency;

        metrics = faultBandMetrics(sd, w, FB_filtered(1:8,:));

        % Extract computed features.
        metricsNames = {'PeakAmplitude6','BandPower6','PeakAmplitude7','BandPower7'};
        featureNames = {'PeakAmp6','BandPower6','PeakAmp7','BandPower7'};
        Vibration_ps_bearing = metrics(:,metricsNames);
        Vibration_ps_bearing = renamevars(Vibration_ps_bearing, metricsNames, featureNames);
    catch
        % Package computed features into a table.
        featureValues = NaN(1,4);
        featureNames = ["PeakAmp6","BandPower6","PeakAmp7","BandPower7"];
        Vibration_ps_bearing = array2table(featureValues,'VariableNames',featureNames);
    end

    % Append computed results to the member table.
    memberResult = [memberResult, ...
        table({Vibration_ps_bearing},'VariableNames',{'Vibration_ps_bearing'})]; %#ok<AGROW>

    %% Write all the results for the current member to the ensemble.
    writeToLastMemberRead(outputEnsemble,memberResult)
end

% Gather all features into a table.
selectedFeatureNames = ["Vibration_ps_bearing/PeakAmp6","Vibration_ps_bearing/BandPower6","Vibration_ps_bearing/PeakAmp7","Vibration_ps_bearing/BandPower7"];
featureTable = readFeatureTable(outputEnsemble,'Features',selectedFeatureNames);

% Set SelectedVariables to select variables to read from the ensemble.
outputEnsemble.SelectedVariables = unique([outputEnsemble.DataVariables;outputEnsemble.ConditionVariables;outputEnsemble.IndependentVariables],'stable');

% Gather results into a table.
outputTable = readall(outputEnsemble);
end
